Fixes #67: Support custom APK bundle formats in `parseAppMeta()`
tweaselORG/appstraction pull request #70
Opened 2023-05-09 12:36 UTC by baltpeter

2023-05-09 14:55 UTC, zner0L requested changes
Nice! I like that you took the time to implement it properly.

2023-05-09 15:43 UTC, baltpeter commented on src/util.ts
> +        const meta = await ipaInfo(appPath as AppPath<'ios'>);
The type is defined in the function definition. But TS doesn't understand that `if`ing on `platform` should narrow the type of `appPath`.

2023-05-11 10:57 UTC, zner0L commented on src/util.ts
> +        const meta = await ipaInfo(appPath as AppPath<'ios'>);
I don’t understand. I was talking about `ipaInfo(string)`, which should be `ipaInfo(AppPath<'ios'>)` instead.

2023-05-15 09:49 UTC, baltpeter commented on src/util.ts
> +        const meta = await ipaInfo(appPath as AppPath<'ios'>);
I mean sure, we can do that. But we'll still need the cast here.

2023-05-15 14:11 UTC, zner0L commented on src/util.ts
> +        const meta = await ipaInfo(appPath as AppPath<'ios'>);
Yes, I know. I liked the casting but it was unnecessary before. That’s what I was referring to.

2023-05-15 14:12 UTC, merged