Fixes #75: Replace libimobiledevice with pymobiledevice3
tweaselORG/appstraction pull request #84
Opened 2023-06-02 14:26 UTC by zner0L

This should be merged after https://github.com/tweaselORG/autopy/issues/5 has been fixed, as the setup of the venv will not work otherwise.

2023-06-02 17:27 UTC, baltpeter requested changes
Very cool.

2023-06-02 17:27 UTC, baltpeter commented on src/ios.ts
> +                    (await python('pymobiledevice3', ['springboard', 'state', 'get'], { reject: false })).exitCode ===
This has a zero exit code even if no device is connected:

```sh
❯ pymobiledevice3 springboard state get
2023-06-02 19:01:32 ryzen pymobiledevice3.__main__[4107830] ERROR Failed to connect to usbmuxd socket. Make sure it's running.
❯ echo $?
0
```

2023-06-02 17:27 UTC, baltpeter commented on src/ios.ts
>      },
Now that we don't need the `if` anymore, you can just return the promise.

2023-06-02 17:27 UTC, baltpeter commented on src/ios.ts
>      },
Same here.

2023-06-05 13:40 UTC, zner0L commented on src/ios.ts
> +                    (await python('pymobiledevice3', ['springboard', 'state', 'get'], { reject: false })).exitCode ===
Again, I cannot reproduce this. Can your provide a little more information?

2023-06-05 15:07 UTC, baltpeter commented on src/ios.ts
> +                    (await python('pymobiledevice3', ['springboard', 'state', 'get'], { reject: false })).exitCode ===
Not quite sure what you're looking for. I installed using `pipx install pymobiledevice3` and when I run `pymobiledevice3 springboard state get` with the iOS 15 phone connected, nothing happens and it just hangs. On iOS 16, it dumps out JSON.

2023-06-06 09:36 UTC, baltpeter commented on src/ios.ts
> +    uninstallApp: (appId) => python('pymobiledevice3', ['apps', 'uninstall', appId]).then(),
Ah, okay.

2023-06-06 11:38 UTC, baltpeter commented on src/ios.ts
> +                    (await python('pymobiledevice3', ['springboard', 'state', 'get'], { reject: false })).exitCode ===
[Newly jailbroken](https://github.com/tweaselORG/meta/issues/4#issuecomment-1578543235), it still works on that device. So I guess the timeout is fine as a workaround.

2023-06-06 14:21 UTC, baltpeter approved these changes

2023-06-06 14:22 UTC, merged